apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demiurge-data
  namespace: demiurge
  labels:
    app: demiurge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
